### ISSUE TITLE
Reverse Ip Domain Module Add

### ISSUE THREAD

**Issue by secfb** [CoffeeJunkiee/Subvenkon#1]
You wrote the code really well. Can this code be edited in reverseip-domain? I tried, I couldn't.
https://www.venkon.us/reverse-ip-domain/

**Comment by caffeinedoom** [comment]
Thanks for the suggestion. I’ll check reverse ip domain in venkon. This Sunday I’ll post an update about it.

**Comment by caffeinedoom** [comment]
Hi @secfb, checking out https://www.venkon.us/reverse-ip-domain/ it gives same assets from https://www.venkon.us/subdomain-lister/, therefore I won't add the module. If you need an explanation on how to gather and grep the data from venkon.us I'd be glad to explain it. If you have other idea, I'd be glad to read it.

**Comment by secfb** [comment]
Bro is not the same. There is a different request in Reverse Ip section.
